apiVersion: apps/v1
kind: Deployment
metadata:
  name: berta-web-app
  namespace: berta-activos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-poc
  template:
    metadata:
      labels:
        app: web-poc
    spec:
      containers:
      - name: nginx
        image: nginx:alpine 
        ports:
        - containerPort: 80