apiVersion: v1
kind: Service
metadata:
  name: berta-web-service
  namespace: berta-activos
spec:
  selector:
    app: web-poc
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP